### ISSUE TITLE
Writing multiple tables 

### ISSUE THREAD

**Issue by lare96** [mwanji/toml4j#35]
If I have a list of tables, represented by a data structure like this

```java
List<Map<String, Object>> myDefinitions = new ArrayList<>();
```

How could I serialize it into valid TOML, so that it looks something like this?

```toml
[[definition]]
name = "myName1"
value = 1
  
[[definition]]
name = "myName2"
value = 2
```

`TomlWriter` afaik only supports the serialization of a single table. When I try and do something like

```java
List<Map<String, Object>> myDefinitions = new ArrayList<>();
new TomlWriter().write(myDefinitions);
```

It throws an exception

`java.lang.IllegalArgumentException: An object of class ArrayList cannot produce valid TOML. Please pass in a Map or a custom type.`

 Is this intended behaviour?
