### ISSUE TITLE
Fallback doesn't work as expected

### ISSUE THREAD

**Issue by Jezza** [mwanji/toml4j#60]
For example:

first.toml
```toml
[metadata.a]
name = "value"

[metadata.b]
name = "value"
```

second.toml
```toml
[metadata.b]
name = "value"

[metadata.c]
name = "value"
```

If I load first.toml, set the result of that to the defaults for second.toml.
```java
Toml defaults = new Toml().read("first.toml");
Toml custom = new Toml(defaults).read("second.toml");
```

I'd expect to be able to access `second.toml`'s version of `b` and `c`, but `first`'s version of `c`.
But right now, it overrides `first.toml`'s declarations, so I can't access 'a'.

It would also be nice if it could get to a point where something like this works:

first.toml
```toml
[metadata.a]
name = "value"
values = [ "value0", "value1" ]

[metadata.b]
name = "value"
```

second.toml
```toml
[metadata.a]
values = [ "value0"]
```

When accessing `metadata.a`, you'd get `second.toml`'s version of values, but inherit the rest from `first.toml`.
